using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

if (args.Length != 2 || args[0] != "--manifest")
{
    Console.Error.WriteLine("Usage: --manifest <json>");
    return 2;
}

try
{
    ExportManifest manifest = JsonSerializer.Deserialize<ExportManifest>(File.ReadAllText(args[1]))
        ?? throw new InvalidOperationException("Invalid production export manifest.");
    var parseOptions = CSharpParseOptions.Default
        .WithLanguageVersion(LanguageVersion.CSharp9)
        .WithPreprocessorSymbols("UNITY_5_3_OR_NEWER");
    foreach (ExportFile file in manifest.Files)
    {
        string source = File.ReadAllText(file.Source, Encoding.UTF8);
        SyntaxTree tree = CSharpSyntaxTree.ParseText(source, parseOptions, file.Source);
        Diagnostic[] errors = tree.GetDiagnostics().Where(x => x.Severity == DiagnosticSeverity.Error).ToArray();
        if (errors.Length > 0)
            throw new InvalidOperationException(string.Join(Environment.NewLine, errors.Select(x => x.ToString())));

        SyntaxNode root = tree.GetRoot();
        SyntaxNode rewritten = new ProductionTriviaRewriter().Visit(root)
            ?? throw new InvalidOperationException($"Failed to rewrite '{file.Source}'.");
        string output = "// <auto-generated production source; do not edit />" + Environment.NewLine +
                        rewritten.NormalizeWhitespace().ToFullString() + Environment.NewLine;
        if (ContainsRtsCode(output))
            throw new InvalidOperationException($"Production output still contains RTS code: {file.Source}");

        Directory.CreateDirectory(Path.GetDirectoryName(file.Output)!);
        File.WriteAllText(file.Output, output, new UTF8Encoding(false));
    }
    return 0;
}
catch (Exception exception)
{
    Console.Error.WriteLine(exception);
    return 1;
}

static bool ContainsRtsCode(string source) =>
    source.Contains("TEngine.RTS", StringComparison.Ordinal) ||
    source.Contains("IScript", StringComparison.Ordinal) ||
    source.Contains("ScriptAnchor", StringComparison.Ordinal) ||
    source.Contains("StaticScriptProvider", StringComparison.Ordinal);

internal sealed class ProductionTriviaRewriter : CSharpSyntaxRewriter
{
    public override SyntaxTrivia VisitTrivia(SyntaxTrivia trivia)
    {
        if (trivia.IsDirective || trivia.IsKind(SyntaxKind.DisabledTextTrivia)) return default;
        return base.VisitTrivia(trivia);
    }
}

internal sealed class ExportManifest
{
    public List<ExportFile> Files { get; set; } = new();
}

internal sealed class ExportFile
{
    public string Source { get; set; } = string.Empty;
    public string Output { get; set; } = string.Empty;
}
