using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.Compilation;
using UnityEngine;

namespace TEngine.RTS.Editor
{
    public static class RtsSourcePromotion
    {
        private const string GENERATED_ASSET_PATH = "Assets/GameScripts/Generated/RTS";
        private const string LEGACY_PRODUCTION_ASSET_PATH = "Assets/GameScripts/Generated/Production";
        private const string LEGACY_RTS_ASSET_PATH = "Assets/GameScripts/Generated/RTS";
        private const string EXPORTER_PROJECT = "Packages/com.tengine.rts/Tools~/ProductionExporter/TEngine.RTS.ProductionExporter.csproj";
        private const string GENERATED_HEADER = "// <auto-generated production source; do not edit />";
        private const string OWNERSHIP_MARKER = ".zero-rts-generated";
        private const string MANIFEST_NAME = "promotion-manifest.json";
        internal const string PENDING_VALIDATION_KEY = "TEngine.RTS.Production.PendingValidation";

        [Serializable]
        private sealed class ExportManifest
        {
            public List<ExportFile> Files = new List<ExportFile>();
        }

        [Serializable]
        private sealed class ExportFile
        {
            public string Source;
            public string Output;
        }

        private sealed class PromotionFile
        {
            public string SourcePath;
            public string RelativePath;
            public string PreviewPath;
            public string TargetPath;
            public string Status;
        }

        private sealed class PromotionPlan
        {
            public string PreviewRoot;
            public string SessionName;
            public int ExportNumber;
            public string TargetAssetPath;
            public string TargetRoot;
            public readonly List<PromotionFile> Files = new List<PromotionFile>();
            public readonly List<string> ObsoleteAssets = new List<string>();
            public readonly List<string> Removals = new List<string>();
            public readonly List<string> Blockers = new List<string>();

            public bool CanApply => Blockers.Count == 0;

            public string Format()
            {
                var text = new StringBuilder();
                text.AppendLine($"Session：{SessionName}");
                text.AppendLine($"输出：{TargetAssetPath}");
                text.AppendLine($"正式源码：{Files.Count}（新增 {Files.Count(x => x.Status == "新增")}，修改 {Files.Count(x => x.Status == "修改")}，不变 {Files.Count(x => x.Status == "不变")}）");
                foreach (PromotionFile file in Files) text.AppendLine($"  [{file.Status}] {file.RelativePath}");
                if (ObsoleteAssets.Count > 0)
                {
                    text.AppendLine("将删除的过期生成文件：");
                    foreach (string path in ObsoleteAssets) text.AppendLine("  " + path);
                }
                if (Removals.Count > 0)
                {
                    text.AppendLine("将排除的开发资产：");
                    foreach (string path in Removals) text.AppendLine("  " + path);
                }
                if (Blockers.Count > 0)
                {
                    text.AppendLine("阻塞项：");
                    foreach (string blocker in Blockers) text.AppendLine("  " + blocker);
                }
                return text.ToString();
            }
        }

        internal static void ShowPreview()
        {
            PromotionPlan plan = BuildPlan();
            string report = plan.Format();
            UnityEngine.Debug.Log("[RTS] Production Dry Run\n" + report);
            EditorUtility.DisplayDialog("RTS Production Dry Run",
                report.Length > 3500 ? report.Substring(0, 3500) + "\n…完整清单见 Console" : report,
                "确定");
        }

        internal static void ExportWithConfirmation()
        {
            PromotionPlan plan = BuildPlan();
            string report = plan.Format();
            if (!plan.CanApply)
            {
                UnityEngine.Debug.LogError("[RTS] Production export blocked:\n" + report);
                EditorUtility.DisplayDialog("无法正式化", "存在阻塞项，详情见 Console。", "确定");
                return;
            }
            if (!EditorUtility.DisplayDialog("确认正式化", report + "\n将先创建可恢复备份。", "导出", "取消")) return;
            ApplyPlan(plan);
        }

        public static void ExportZeroRtsForBatch()
        {
            PromotionPlan plan = BuildPlan();
            if (!plan.CanApply) throw new InvalidOperationException(plan.Format());
            ApplyPlan(plan);
        }

        [Obsolete("Use ExportZeroRtsForBatch instead.")]
        public static void PromoteForBatch() => ExportZeroRtsForBatch();

        internal static string GetNextTargetAssetPath()
        {
            RtsProjectSettings settings = RtsProjectSettings.instance;
            string session = SanitizeSessionName(settings.ActiveSessionId);
            string sessionAssetPath = GENERATED_ASSET_PATH + "/" + session;
            int exportNumber = FindNextExportNumber(Path.Combine(settings.ProjectRoot, sessionAssetPath));
            return sessionAssetPath + "/Export" + exportNumber.ToString("0000");
        }

        internal static void RestoreLatestBackup()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) return;
            string projectRoot = RtsProjectSettings.instance.ProjectRoot;
            string backupBase = Path.Combine(projectRoot, "Library", "TEngineRTS", "PromotionBackups");
            string latest = Directory.Exists(backupBase)
                ? Directory.GetDirectories(backupBase)
                    .Where(path => File.Exists(Path.Combine(path, "backup.complete")) &&
                                   Directory.Exists(Path.Combine(path, "GeneratedRTS")))
                    .OrderByDescending(path => path, StringComparer.Ordinal).FirstOrDefault()
                : null;
            if (string.IsNullOrEmpty(latest))
            {
                EditorUtility.DisplayDialog("RTS Restore", "没有可恢复的正式化备份。", "确定");
                return;
            }
            if (!EditorUtility.DisplayDialog("恢复正式化备份", Path.GetFileName(latest), "恢复", "取消")) return;

            DeleteOwnedGeneratedExports();
            DeleteOwnedLegacyAsset();
            RestoreDirectory(Path.Combine(latest, "GeneratedRTS"), Path.Combine(projectRoot, GENERATED_ASSET_PATH));
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            Log.Info("[RTS] Restored production backup: {0}", latest);
        }

        private static PromotionPlan BuildPlan()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
                throw new InvalidOperationException("Exit Play Mode before previewing or exporting production sources.");

            RtsProjectSettings settings = RtsProjectSettings.instance;
            string projectRoot = settings.ProjectRoot;
            string sessionName = SanitizeSessionName(settings.ActiveSessionId);
            string sessionAssetPath = GENERATED_ASSET_PATH + "/" + sessionName;
            int exportNumber = FindNextExportNumber(Path.Combine(projectRoot, sessionAssetPath));
            string targetAssetPath = sessionAssetPath + "/Export" + exportNumber.ToString("0000");
            string targetRoot = Path.Combine(projectRoot, targetAssetPath);
            string previewBase = Path.Combine(projectRoot, "Library", "TEngineRTS", "ProductionPreview");
            RecreateSafeLibraryDirectory(previewBase, projectRoot);
            string previewRoot = Path.Combine(previewBase, Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(previewRoot);

            var plan = new PromotionPlan
            {
                PreviewRoot = previewRoot,
                SessionName = settings.ActiveSessionId,
                ExportNumber = exportNumber,
                TargetAssetPath = targetAssetPath,
                TargetRoot = targetRoot
            };
            string[] roots = RtsSessionCatalog.ResolveActiveOwnedSourceRoots().Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
            if (roots.Length == 0) plan.Blockers.Add("未配置源码目录。");
            var manifest = new ExportManifest();
            var targetKeys = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string root in roots)
            {
                if (!Directory.Exists(root))
                {
                    plan.Blockers.Add("源码目录不存在：" + root);
                    continue;
                }
                string prefix = roots.Length == 1 ? string.Empty : SanitizeSegment(new DirectoryInfo(root).Name);
                foreach (string source in Directory.GetFiles(root, "*.cs", SearchOption.AllDirectories))
                {
                    string relative = source.Substring(root.Length).TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
                    if (!string.IsNullOrEmpty(prefix)) relative = Path.Combine(prefix, relative);
                    if (!targetKeys.Add(relative))
                    {
                        plan.Blockers.Add("多个源码映射到同一正式路径：" + relative);
                        continue;
                    }
                    string preview = Path.Combine(previewRoot, relative);
                    string target = Path.Combine(targetRoot, relative);
                    manifest.Files.Add(new ExportFile { Source = source, Output = preview });
                    plan.Files.Add(new PromotionFile
                    {
                        SourcePath = source,
                        RelativePath = relative.Replace('\\', '/'),
                        PreviewPath = preview,
                        TargetPath = target
                    });
                }
            }
            if (manifest.Files.Count == 0) plan.Blockers.Add("没有找到可正式化的 C# 源码。");

            if (plan.Blockers.Count == 0)
            {
                try
                {
                    string manifestPath = Path.Combine(previewRoot, "export-manifest.json");
                    File.WriteAllText(manifestPath, JsonUtility.ToJson(manifest, true), new UTF8Encoding(false));
                    RunProductionExporter(projectRoot, manifestPath);
                    foreach (PromotionFile file in plan.Files)
                    {
                        file.Status = !File.Exists(file.TargetPath) ? "新增" :
                            FilesEqual(file.PreviewPath, file.TargetPath) ? "不变" : "修改";
                    }
                    ValidateProductionArchitecture(plan);
                }
                catch (Exception exception) { plan.Blockers.Add(exception.Message); }
            }

            ValidateExistingOutput(plan, targetRoot, projectRoot);
            ValidateCleanupTargets(plan, projectRoot);
            ValidateSessionDependencies(plan, projectRoot);
            ValidateSessionReadiness(plan);
            plan.Blockers.AddRange(RtsDummySandbox.FindBuildBlockers());
            return plan;
        }

        private static void ValidateSessionDependencies(PromotionPlan plan, string projectRoot)
        {
            string[] dependencies = RtsSessionCatalog.Active?.Descriptor.sessionDependencies ?? Array.Empty<string>();
            foreach (string dependency in dependencies)
            {
                string dependencyRoot = Path.Combine(projectRoot, GENERATED_ASSET_PATH, SanitizeSessionName(dependency));
                bool hasActiveExport = Directory.Exists(dependencyRoot) &&
                                       Directory.GetFiles(dependencyRoot, "*.cs", SearchOption.AllDirectories).Length > 0;
                if (!hasActiveExport)
                    plan.Blockers.Add($"依赖 Session '{dependency}' 尚无活动正式 Export；请先正式化依赖，避免复制其源码。");
            }
        }

        private static void ValidateSessionReadiness(PromotionPlan plan)
        {
            RtsSessionInfo session = RtsSessionCatalog.Active;
            if (session == null)
            {
                plan.Blockers.Add("没有活动 Session。");
                return;
            }
            string analysis = File.Exists(session.ReuseAnalysisPath) ? File.ReadAllText(session.ReuseAnalysisPath) : string.Empty;
            if (string.IsNullOrWhiteSpace(analysis) || analysis.IndexOf("not analyzed", StringComparison.OrdinalIgnoreCase) >= 0)
                plan.Blockers.Add("Agent 尚未完成 reuse-analysis.md；请先分析正式实现、复用点和新增边界。");
            if ((session.Descriptor.baseModules?.Length ?? 0) > 0 && string.IsNullOrWhiteSpace(session.Descriptor.baseRevision))
                plan.Blockers.Add("Session 声明了正式 baseModules，但没有记录 baseRevision/指纹。");
        }

        private static void ValidateProductionArchitecture(PromotionPlan plan)
        {
            var forbidden = new Dictionary<string, string>
            {
                { "RuntimeInitializeOnLoadMethod", "自动启动器" },
                { "GameObject.CreatePrimitive", "硬编码 Primitive" },
                { "Object.FindObjectOfType", "隐式场景查找" },
                { "Resources.Load", "硬编码 Resources 路径" },
                { "Shader.Find", "硬编码 Shader 查找" }
            };
            foreach (PromotionFile file in plan.Files)
            {
                string source = File.ReadAllText(file.PreviewPath);
                foreach (KeyValuePair<string, string> entry in forbidden)
                    if (source.Contains(entry.Key, StringComparison.Ordinal))
                        plan.Blockers.Add($"{file.RelativePath} 包含{entry.Value}（{entry.Key}）；请先改为 Data/Adaptor/View 与稳定资产映射。");
            }
        }

        private static void ApplyPlan(PromotionPlan plan)
        {
            if (!plan.CanApply) throw new InvalidOperationException(plan.Format());
            string projectRoot = RtsProjectSettings.instance.ProjectRoot;
            string lockDirectory = Path.Combine(projectRoot, "Library", "TEngineRTS", "locks");
            Directory.CreateDirectory(lockDirectory);
            using var promotionLock = new FileStream(Path.Combine(lockDirectory, "production-output.lock"), FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
            string backup = CreateBackup(projectRoot);
            try
            {
                DeactivatePreviousExports(Path.GetDirectoryName(plan.TargetRoot), plan.TargetRoot);
                string targetRoot = plan.TargetRoot;
                Directory.CreateDirectory(targetRoot);
                File.WriteAllText(Path.Combine(targetRoot, OWNERSHIP_MARKER), GENERATED_HEADER, new UTF8Encoding(false));
                foreach (PromotionFile file in plan.Files)
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(file.TargetPath));
                    if (file.Status != "不变") File.Copy(file.PreviewPath, file.TargetPath, true);
                }
                WritePromotionManifest(targetRoot, plan);
                RemoveLegacyRtsOutput(projectRoot);
                SessionState.SetBool(PENDING_VALIDATION_KEY, true);
                AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
                Log.Info("[RTS] Zero-RTS production export completed.\n{0}", plan.Format());
            }
            catch
            {
                DeleteOwnedGeneratedExports();
                DeleteOwnedLegacyAsset();
                RestoreDirectory(Path.Combine(backup, "GeneratedRTS"), Path.Combine(projectRoot, GENERATED_ASSET_PATH));
                AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
                throw;
            }
        }

        private static void ValidateExistingOutput(PromotionPlan plan, string targetRoot, string projectRoot)
        {
            if (!Directory.Exists(targetRoot)) return;
            if (!File.Exists(Path.Combine(targetRoot, OWNERSHIP_MARKER)))
            {
                plan.Blockers.Add($"正式输出目录没有所有权标记，拒绝修改：{plan.TargetAssetPath}");
                return;
            }
            var expected = new HashSet<string>(plan.Files.Select(x => Path.GetFullPath(x.TargetPath)), StringComparer.OrdinalIgnoreCase);
            foreach (string source in Directory.GetFiles(targetRoot, "*.cs", SearchOption.AllDirectories))
            {
                if (expected.Contains(Path.GetFullPath(source))) continue;
                if (File.ReadLines(source).FirstOrDefault() != GENERATED_HEADER)
                    plan.Blockers.Add("发现非工具生成的正式源码，拒绝删除：" + MakeProjectRelative(projectRoot, source));
                else
                    plan.ObsoleteAssets.Add(MakeProjectRelative(projectRoot, source));
            }
        }

        private static void ValidateCleanupTargets(PromotionPlan plan, string projectRoot)
        {
            string legacyRoot = Path.Combine(projectRoot, LEGACY_RTS_ASSET_PATH);
            if (Directory.Exists(legacyRoot) && IsOwnedLegacyRoot(legacyRoot))
            {
                plan.Removals.Add(LEGACY_RTS_ASSET_PATH + "（仅旧根产物）");
            }
            string legacyProduction = Path.Combine(projectRoot, LEGACY_PRODUCTION_ASSET_PATH);
            if (Directory.Exists(legacyProduction))
                plan.Blockers.Add("旧正式输出仍在活动目录，请先迁移或恢复后再使用 Session 正式化：" + LEGACY_PRODUCTION_ASSET_PATH);
        }

        private static void RunProductionExporter(string projectRoot, string manifestPath)
        {
            string project = Path.Combine(projectRoot, EXPORTER_PROJECT);
            var process = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = "dotnet",
                    Arguments = "run --project " + Quote(project) + " --configuration Release -- --manifest " + Quote(manifestPath),
                    WorkingDirectory = projectRoot,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true
                }
            };
            process.Start();
            try
            {
                Task<string> output = process.StandardOutput.ReadToEndAsync();
                Task<string> error = process.StandardError.ReadToEndAsync();
                process.WaitForExit();
                Task.WaitAll(output, error);
                if (process.ExitCode != 0) throw new InvalidOperationException(error.Result + output.Result);
            }
            finally { process.Dispose(); }
        }

        private static string CreateBackup(string projectRoot)
        {
            string root = Path.Combine(projectRoot, "Library", "TEngineRTS", "PromotionBackups",
                DateTime.UtcNow.ToString("yyyyMMddHHmmssfff"));
            Directory.CreateDirectory(root);
            Directory.CreateDirectory(Path.Combine(root, "GeneratedRTS"));
            BackupDirectory(Path.Combine(projectRoot, GENERATED_ASSET_PATH), Path.Combine(root, "GeneratedRTS"));
            File.WriteAllText(Path.Combine(root, "backup.complete"), DateTime.UtcNow.ToString("O"), new UTF8Encoding(false));
            return root;
        }

        private static void WritePromotionManifest(string targetRoot, PromotionPlan plan)
        {
            var text = new StringBuilder();
            text.AppendLine("{");
            text.AppendLine("  \"generatedBy\": \"TEngine RTS\",");
            text.AppendLine("  \"session\": \"" + EscapeJson(plan.SessionName) + "\",");
            text.AppendLine("  \"exportNumber\": " + plan.ExportNumber + ",");
            text.AppendLine("  \"integration\": \"Incremental module; existing project startup owns creation and disposal. No bootstrap or scene mutation was generated.\",");
            text.AppendLine("  \"stableAssetMapping\": \"" + EscapeJson(RtsDummySandbox.ManifestPath) + "\",");
            string[] dependencies = RtsSessionCatalog.Active?.Descriptor.sessionDependencies ?? Array.Empty<string>();
            text.AppendLine("  \"sessionDependencies\": [" + string.Join(", ", dependencies.Select(value => "\"" + EscapeJson(value) + "\"")) + "],");
            text.AppendLine("  \"requiredCapabilities\": [\"IRtsWorldServiceV1\", \"IRtsTargetQueryV1\", \"IRtsDamageServiceV1\"],");
            text.AppendLine("  \"files\": [");
            for (int i = 0; i < plan.Files.Count; i++)
            {
                PromotionFile file = plan.Files[i];
                text.Append("    { \"path\": \"").Append(EscapeJson(file.RelativePath)).Append("\", \"sha256\": \"")
                    .Append(ComputeSha256(file.TargetPath)).Append("\" }");
                text.AppendLine(i + 1 == plan.Files.Count ? string.Empty : ",");
            }
            text.AppendLine("  ]");
            text.AppendLine("}");
            File.WriteAllText(Path.Combine(targetRoot, MANIFEST_NAME), text.ToString(), new UTF8Encoding(false));
        }

        private static void RemoveLegacyRtsOutput(string projectRoot)
        {
            string root = Path.Combine(projectRoot, LEGACY_RTS_ASSET_PATH);
            if (Directory.Exists(root) && IsOwnedLegacyRoot(root)) DeleteOwnedLegacyAsset();
        }

        private static void DeleteOwnedLegacyAsset()
        {
            string root = Path.Combine(RtsProjectSettings.instance.ProjectRoot, LEGACY_RTS_ASSET_PATH);
            if (!Directory.Exists(root)) return;
            if (!IsOwnedLegacyRoot(root)) return;
            string marker = Path.Combine(root, ".rts-generated");
            string registry = Path.Combine(root, "RtsStaticRegistry.g.cs");
            if (File.Exists(marker)) File.Delete(marker);
            if (File.Exists(marker + ".meta")) File.Delete(marker + ".meta");
            if (File.Exists(registry)) File.Delete(registry);
            if (File.Exists(registry + ".meta")) File.Delete(registry + ".meta");
            string scripts = Path.Combine(root, "Scripts");
            if (Directory.Exists(scripts)) Directory.Delete(scripts, true);
            if (File.Exists(scripts + ".meta")) File.Delete(scripts + ".meta");
        }

        private static bool IsOwnedLegacyRoot(string root)
        {
            string registry = Path.Combine(root, "RtsStaticRegistry.g.cs");
            return File.Exists(Path.Combine(root, ".rts-generated")) ||
                   File.Exists(registry) && File.ReadLines(registry).FirstOrDefault() ==
                   "// <auto-generated by TEngine RTS source promotion />";
        }

        private static void DeactivatePreviousExports(string sessionRoot, string nextTargetRoot)
        {
            if (string.IsNullOrWhiteSpace(sessionRoot) || !Directory.Exists(sessionRoot)) return;
            string excluded = Path.GetFullPath(nextTargetRoot) + Path.DirectorySeparatorChar;
            foreach (string source in Directory.GetFiles(sessionRoot, "*.cs", SearchOption.AllDirectories))
            {
                string fullSource = Path.GetFullPath(source);
                if (fullSource.StartsWith(excluded, StringComparison.OrdinalIgnoreCase)) continue;
                if (!HasOwnedAncestor(fullSource, sessionRoot)) continue;
                string snapshot = source + ".snapshot";
                if (File.Exists(snapshot))
                    throw new InvalidOperationException("Cannot archive an active export because its snapshot already exists: " + snapshot);
                File.Move(source, snapshot);
                string meta = source + ".meta";
                if (File.Exists(meta)) File.Move(meta, snapshot + ".meta");
            }
        }

        private static bool HasOwnedAncestor(string path, string generatedRoot)
        {
            DirectoryInfo directory = new FileInfo(path).Directory;
            string boundary = Path.GetFullPath(generatedRoot).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
            while (directory != null && directory.FullName.StartsWith(boundary, StringComparison.OrdinalIgnoreCase))
            {
                if (File.Exists(Path.Combine(directory.FullName, OWNERSHIP_MARKER))) return true;
                if (directory.FullName.Equals(boundary, StringComparison.OrdinalIgnoreCase)) break;
                directory = directory.Parent;
            }
            return false;
        }

        private static void DeleteOwnedGeneratedExports()
        {
            string projectRoot = RtsProjectSettings.instance.ProjectRoot;
            string generatedRoot = Path.Combine(projectRoot, GENERATED_ASSET_PATH);
            if (!Directory.Exists(generatedRoot)) return;
            string[] ownedDirectories = Directory.GetFiles(generatedRoot, OWNERSHIP_MARKER, SearchOption.AllDirectories)
                .Select(Path.GetDirectoryName)
                .OrderByDescending(path => path.Length)
                .ToArray();
            foreach (string directory in ownedDirectories)
            {
                if (!Directory.Exists(directory)) continue;
                string assetPath = MakeProjectRelative(projectRoot, directory);
                if (AssetDatabase.DeleteAsset(assetPath)) continue;
                if (!File.Exists(Path.Combine(directory, OWNERSHIP_MARKER)))
                    throw new InvalidOperationException("Refusing fallback deletion without ownership marker: " + assetPath);
                Directory.Delete(directory, true);
                if (File.Exists(directory + ".meta")) File.Delete(directory + ".meta");
            }
        }

        private static int FindNextExportNumber(string sessionRoot)
        {
            if (!Directory.Exists(sessionRoot)) return 1;
            int maximum = 0;
            foreach (string directory in Directory.GetDirectories(sessionRoot, "Export*", SearchOption.TopDirectoryOnly))
            {
                string suffix = Path.GetFileName(directory).Substring("Export".Length);
                if (int.TryParse(suffix, out int number)) maximum = Math.Max(maximum, number);
            }
            return maximum + 1;
        }

        private static string SanitizeSessionName(string value)
        {
            string sanitized = SanitizeSegment(string.IsNullOrWhiteSpace(value) ? "DefaultSession" : value.Trim());
            return string.IsNullOrWhiteSpace(sanitized) ? "DefaultSession" : sanitized;
        }

        private static string EscapeJson(string value) =>
            (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string ComputeSha256(string path)
        {
            using SHA256 algorithm = SHA256.Create();
            return string.Concat(algorithm.ComputeHash(File.ReadAllBytes(path)).Select(value => value.ToString("x2")));
        }

        private static void RecreateSafeLibraryDirectory(string directory, string projectRoot)
        {
            string libraryRoot = Path.GetFullPath(Path.Combine(projectRoot, "Library", "TEngineRTS")) + Path.DirectorySeparatorChar;
            string resolved = Path.GetFullPath(directory);
            if (!resolved.StartsWith(libraryRoot, StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("Unsafe preview directory: " + resolved);
            if (Directory.Exists(resolved)) Directory.Delete(resolved, true);
            Directory.CreateDirectory(resolved);
        }

        private static bool FilesEqual(string left, string right) =>
            File.ReadAllBytes(left).SequenceEqual(File.ReadAllBytes(right));

        private static string MakeProjectRelative(string projectRoot, string path) =>
            Path.GetRelativePath(projectRoot, path).Replace('\\', '/');

        private static string SanitizeSegment(string value) =>
            new string(value.Select(character => char.IsLetterOrDigit(character) || character == '_' ? character : '_').ToArray());

        private static string Quote(string value) => "\"" + value.Replace("\"", "\\\"") + "\"";

        private static void BackupDirectory(string source, string target)
        {
            if (!Directory.Exists(source)) return;
            foreach (string directory in Directory.GetDirectories(source, "*", SearchOption.AllDirectories))
                Directory.CreateDirectory(Path.Combine(target, directory.Substring(source.Length)
                    .TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)));
            Directory.CreateDirectory(target);
            foreach (string file in Directory.GetFiles(source, "*", SearchOption.AllDirectories))
            {
                string destination = Path.Combine(target, file.Substring(source.Length)
                    .TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));
                Directory.CreateDirectory(Path.GetDirectoryName(destination));
                File.Copy(file, destination, true);
            }
        }

        private static void RestoreDirectory(string source, string target) => BackupDirectory(source, target);
        private static void BackupFile(string source, string target)
        {
            if (!File.Exists(source)) return;
            Directory.CreateDirectory(Path.GetDirectoryName(target));
            File.Copy(source, target, true);
        }
        private static void RestoreFile(string source, string target) => BackupFile(source, target);
    }

    [InitializeOnLoad]
    internal static class RtsPostExportValidator
    {
        static RtsPostExportValidator()
        {
            if (SessionState.GetBool(RtsSourcePromotion.PENDING_VALIDATION_KEY, false))
                EditorApplication.delayCall += Validate;
        }

        private static void Validate()
        {
            SessionState.EraseBool(RtsSourcePromotion.PENDING_VALIDATION_KEY);
            try
            {
                RtsZeroBuildGuard.ValidateOrThrow();
                Log.Info("[RTS] Post-export Unity compilation and Zero-RTS validation passed.");
            }
            catch (Exception exception)
            {
                UnityEngine.Debug.LogError("[RTS] Post-export validation failed:\n" + exception);
            }
        }
    }

    internal sealed class RtsZeroBuildGuard : IPreprocessBuildWithReport
    {
        private const string PACKAGE_PREFIX = "Packages/com.tengine.rts/";
        private const string LEGACY_OUTPUT_PATH = "Assets/GameScripts/Generated/RTS";
        private const string LEGACY_PRODUCTION_OUTPUT_PATH = "Assets/GameScripts/Generated/Production";
        private const string PRODUCTION_OUTPUT_PATH = "Assets/GameScripts/Generated/RTS";
        private const string RTS_TEST_SCENE_PATH = "Assets/AssetRaw/Scenes/RTSTest.unity";

        public int callbackOrder => -10000;
        public void OnPreprocessBuild(BuildReport report) => ValidateOrThrow();

        internal static void ValidateFromControlCenter()
        {
            ValidateOrThrow();
            Log.Info("[RTS] Zero-RTS Player validation passed.");
        }

        public static void ValidateForBatch() => ValidateOrThrow();

        internal static void ValidateOrThrow()
        {
            RtsDummySandbox.ValidateBuildOrThrow();
            IReadOnlyList<string> failures = FindFailures();
            if (failures.Count == 0) return;
            throw new BuildFailedException("Zero-RTS Player validation failed:\n- " + string.Join("\n- ", failures));
        }

        internal static IReadOnlyList<string> FindFailures()
        {
            var failures = new List<string>();
            ValidatePlayerAssemblies(failures);
            string legacyRoot = Path.Combine(RtsProjectSettings.instance.ProjectRoot, LEGACY_OUTPUT_PATH);
            if (File.Exists(Path.Combine(legacyRoot, ".rts-generated")) || File.Exists(Path.Combine(legacyRoot, "RtsStaticRegistry.g.cs")))
                failures.Add("Legacy static Provider output still exists at RTS root: " + LEGACY_OUTPUT_PATH);
            if (AssetDatabase.IsValidFolder(LEGACY_PRODUCTION_OUTPUT_PATH))
                failures.Add("Legacy production output must be migrated under the isolated RTS root: " + LEGACY_PRODUCTION_OUTPUT_PATH);
            ValidateProductionSources(failures);
            ValidateAssetDependencies(failures);
            return failures;
        }

        private static void ValidateProductionSources(ICollection<string> failures)
        {
            string root = Path.Combine(RtsProjectSettings.instance.ProjectRoot, PRODUCTION_OUTPUT_PATH);
            if (!Directory.Exists(root)) return;
            foreach (string sourcePath in Directory.GetFiles(root, "*.cs", SearchOption.AllDirectories))
            {
                string source = File.ReadAllText(sourcePath);
                if (source.Contains("TEngine.RTS", StringComparison.Ordinal) || source.Contains("IScript", StringComparison.Ordinal) ||
                    source.Contains("ScriptAnchor", StringComparison.Ordinal) || source.Contains("StaticScriptProvider", StringComparison.Ordinal))
                    failures.Add("Production source still contains RTS-specific code: " + sourcePath);
                if (source.Contains("RuntimeInitializeOnLoadMethod", StringComparison.Ordinal) ||
                    source.Contains("GameObject.CreatePrimitive", StringComparison.Ordinal) ||
                    source.Contains("Object.FindObjectOfType", StringComparison.Ordinal) ||
                    source.Contains("Resources.Load", StringComparison.Ordinal))
                    failures.Add("Production source bypasses incremental Data/Adaptor/View integration: " + sourcePath);
            }
        }

        private static void ValidatePlayerAssemblies(ICollection<string> failures)
        {
            foreach (UnityEditor.Compilation.Assembly assembly in CompilationPipeline.GetAssemblies(AssembliesType.Player))
            {
                if (IsUnityTestAssembly(assembly.name)) continue;
                if (IsRtsAssembly(assembly.name)) failures.Add("RTS assembly is included in Player compilation: " + assembly.name);
                foreach (UnityEditor.Compilation.Assembly reference in assembly.assemblyReferences)
                    if (IsRtsAssembly(reference.name)) failures.Add($"Player assembly '{assembly.name}' references '{reference.name}'.");
            }
        }

        private static bool IsUnityTestAssembly(string assemblyName)
        {
            string definitionPath = CompilationPipeline.GetAssemblyDefinitionFilePathFromAssemblyName(assemblyName);
            if (string.IsNullOrWhiteSpace(definitionPath)) return false;
            string absolutePath = Path.Combine(RtsProjectSettings.instance.ProjectRoot, definitionPath);
            if (!File.Exists(absolutePath)) return false;
            string definition = File.ReadAllText(absolutePath);
            return definition.Contains("\"TestAssemblies\"", StringComparison.Ordinal);
        }

        private static void ValidateAssetDependencies(ICollection<string> failures)
        {
            IEnumerable<string> assets = AssetDatabase.FindAssets("t:Scene", new[] { "Assets" })
                .Concat(AssetDatabase.FindAssets("t:Prefab", new[] { "Assets" }))
                .Concat(AssetDatabase.FindAssets("t:ScriptableObject", new[] { "Assets" }))
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(path => !path.Equals(RTS_TEST_SCENE_PATH, StringComparison.OrdinalIgnoreCase) &&
                               !path.StartsWith(RtsDummySandbox.AssetRootBase + "/", StringComparison.OrdinalIgnoreCase))
                .Distinct(StringComparer.Ordinal);
            foreach (string asset in assets)
            {
                string dependency = AssetDatabase.GetDependencies(asset, true).FirstOrDefault(path =>
                    path.StartsWith(PACKAGE_PREFIX + "Contracts/", StringComparison.OrdinalIgnoreCase) ||
                    path.StartsWith(PACKAGE_PREFIX + "Runtime/", StringComparison.OrdinalIgnoreCase));
                if (!string.IsNullOrEmpty(dependency)) failures.Add($"Asset '{asset}' depends on RTS runtime asset '{dependency}'.");
            }
        }

        private static bool IsRtsAssembly(string name) =>
            !string.IsNullOrEmpty(name) && name.StartsWith("TEngine.RTS", StringComparison.Ordinal);
    }

    public static class RtsCiBuild
    {
        public static void BuildPlayerForBatch()
        {
            string[] args = Environment.GetCommandLineArgs();
            string output = ReadArgument(args, "-rtsBuildOutput") ??
                            Path.Combine(RtsProjectSettings.instance.ProjectRoot, "Temp", "RTSPlayerBuild");
            string targetName = ReadArgument(args, "-rtsBuildTarget") ?? EditorUserBuildSettings.activeBuildTarget.ToString();
            if (!Enum.TryParse(targetName, true, out BuildTarget target))
                throw new ArgumentException("Unknown build target: " + targetName);
            BuildTargetGroup group = BuildPipeline.GetBuildTargetGroup(target);
            NamedBuildTarget namedBuildTarget = NamedBuildTarget.FromBuildTargetGroup(group);
            ScriptingImplementation previousBackend = PlayerSettings.GetScriptingBackend(namedBuildTarget);
            bool forceIl2Cpp = args.Any(x => x.Equals("-rtsForceIl2Cpp", StringComparison.OrdinalIgnoreCase));
            try
            {
                if (forceIl2Cpp) PlayerSettings.SetScriptingBackend(namedBuildTarget, ScriptingImplementation.IL2CPP);
                string[] scenes = EditorBuildSettings.scenes.Where(scene => scene.enabled).Select(scene => scene.path).ToArray();
                if (scenes.Length == 0) throw new InvalidOperationException("No enabled Player scenes were found.");
                string outputParent = Path.GetDirectoryName(output);
                if (!string.IsNullOrEmpty(outputParent)) Directory.CreateDirectory(outputParent);
                BuildReport report = BuildPipeline.BuildPlayer(new BuildPlayerOptions
                {
                    scenes = scenes,
                    locationPathName = output,
                    target = target,
                    options = BuildOptions.None
                });
                if (report.summary.result != BuildResult.Succeeded)
                    throw new InvalidOperationException("Player build failed: " + report.summary.result);
                IReadOnlyList<string> residues = ScanBuildOutput(output);
                if (residues.Count > 0)
                    throw new InvalidOperationException("RTS residue was found in Player output:\n" + string.Join("\n", residues));
                Log.Info("[RTS] Player build and output scan passed: {0}", output);
            }
            finally
            {
                if (forceIl2Cpp) PlayerSettings.SetScriptingBackend(namedBuildTarget, previousBackend);
            }
        }

        internal static IReadOnlyList<string> ScanBuildOutput(string output)
        {
            string root = Directory.Exists(output) ? output : Path.GetDirectoryName(output);
            if (string.IsNullOrEmpty(root) || !Directory.Exists(root)) throw new DirectoryNotFoundException(root ?? output);
            var failures = new List<string>();
            foreach (string file in Directory.GetFiles(root, "*", SearchOption.AllDirectories))
            {
                if (Path.GetFileName(file).IndexOf("TEngine.RTS", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    failures.Add("文件名：" + file);
                    continue;
                }
                long length = new FileInfo(file).Length;
                if (length == 0) continue;
                if (ContainsBytes(file, Encoding.UTF8.GetBytes("TEngine.RTS")) ||
                    ContainsBytes(file, Encoding.Unicode.GetBytes("TEngine.RTS"))) failures.Add("内容：" + file);
            }
            return failures;
        }

        private static bool ContainsBytes(string path, byte[] needle)
        {
            const int BUFFER_SIZE = 64 * 1024;
            byte[] buffer = new byte[BUFFER_SIZE + needle.Length];
            int carry = 0;
            using (FileStream stream = File.OpenRead(path))
            {
                int read;
                while ((read = stream.Read(buffer, carry, BUFFER_SIZE)) > 0)
                {
                    int length = carry + read;
                    for (int i = 0; i <= length - needle.Length; i++)
                    {
                        bool match = true;
                        for (int j = 0; j < needle.Length; j++)
                            if (buffer[i + j] != needle[j]) { match = false; break; }
                        if (match) return true;
                    }
                    carry = Math.Min(needle.Length - 1, length);
                    Buffer.BlockCopy(buffer, length - carry, buffer, 0, carry);
                }
            }
            return false;
        }

        private static string ReadArgument(string[] args, string name)
        {
            for (int i = 0; i + 1 < args.Length; i++)
                if (args[i].Equals(name, StringComparison.OrdinalIgnoreCase)) return args[i + 1];
            return null;
        }
    }
}
